"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Standard Library Imports
import logging
import os
from datetime import timedelta
from pathlib import Path

# Third Party Library Imports
from dotenv import load_dotenv


def is_true_fn(x):
    return x in [1, "1", "True", "true"]


DEBUG = os.environ.get("ENV", "dev") == "dev"
HOST_URL = os.environ.get("HOST_URL", "http://localhost:8000")
APP_NAME = "app"

if DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {"console": {"class": "logging.StreamHandler"}},
        "loggers": {
            "django": {"handlers": ["console"], "level": "INFO"},
            f"{APP_NAME}": {"handlers": ["console"], "level": "DEBUG"},
        },
    }
else:
    # Third Party Library Imports
    from google.cloud.logging import Client

    client = Client()
    client.setup_logging()
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "cloud": {"class": "google.cloud.logging.handlers.CloudLoggingHandler", "client": client},
            "console": {"class": "logging.StreamHandler"},
        },
        "loggers": {
            "django": {"handlers": ["cloud", "console"], "level": "INFO", "propagate": True},
            "django.request": {"handlers": ["cloud"], "level": "ERROR", "propagate": False},
        },
    }

logger = logging.getLogger(__name__)

# Load base environment file
env_file = ".env.dev" if DEBUG else ".env.prod"
env_loaded = load_dotenv(env_file, override=False, verbose=True)
if env_loaded:
    print(f"Loaded base ENVs from {env_file}")

# Load local secrets override (only in development)
# This file is gitignored and should contain your actual secrets
if DEBUG:
    secrets_file = ".env.dev.secrets"
    if os.path.exists(secrets_file):
        secrets_loaded = load_dotenv(secrets_file, override=True, verbose=True)
        if secrets_loaded:
            print(f"Loaded secret overrides from {secrets_file}")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.environ.get("SECRET_KEY", "-c&qt=71oi^e5s8(ene*$b89^#%*0xeve$x_trs91veok9#0h0")

LOG_TO_FILE = is_true_fn(os.environ.get("LOG_TO_FILE")) if DEBUG else True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "graphene_django",
    "django_extensions",
    "debug_toolbar",
    "accounts",
    "deploy",
    "tasks",
    "corsheaders",
    "django_filters",
]

AUTH_USER_MODEL = "accounts.User"
LOGOUT_REDIRECT_URL = "/dev/login"

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "utils.middleware.debug_toolbar.NonHtmlDebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "accounts.middlewares.jwt.JWTMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = f"{APP_NAME}.urls"
GCP_PROJECT_ID = os.environ.get("GCP_PROJECT_ID", "your-gcp-project-id")
GCP_REGION = os.environ.get("GCP_REGION", "us-central1")

if DEBUG:
    SESSION_COOKIE_SAMESITE = None
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []
    CSRF_COOKIE_SAMESITE = None
    CSRF_TRUSTED_ORIGINS = []
    SECURE_HSTS_SECONDS = None
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SECURE = True  # Use secure cookies for sessions
    CSRF_COOKIE_SECURE = True  # Use secure cookies for CSRF tokens
    CORS_ALLOWED_ORIGINS = [HOST_URL]
    CSRF_TRUSTED_ORIGINS = [HOST_URL, "http://localhost:8081"]
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOWED_ORIGIN_REGEXES = [r"http://([\w\-]+.)?localhost:[0-9]{4}"]


# settings.py
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / f"{APP_NAME}/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = f"{APP_NAME}.wsgi.application"
ASGI_APPLICATION = f"{APP_NAME}.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "NAME": os.environ.get("POSTGRES_DB", "django_db"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
        "PORT": os.environ.get("POSTGRES_PORT", 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

GRAPHENE = {
    "SCHEMA": f"{APP_NAME}.graphql.schema.schema",
    "MIDDLEWARE": [
        f"{APP_NAME}.graphql.middlewares.ErrorLoggingMiddleware",
        "graphene_django.debug.DjangoDebugMiddleware",
    ],
}

GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": False,
    "JWT_EXPIRATION_DELTA": timedelta(days=30),
    "JWT_REFRESH_EXPIRATION_DELTA": timedelta(days=30),
    "JWT_AUTH_HEADER_PREFIX": "Bearer",
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

if not DEBUG or is_true_fn(os.environ.get("USE_GCS")):
    GS_BUCKET_NAME = os.environ.get("GCS_BUCKET_NAME", "your-gcs-bucket")

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        },
        "staticfiles": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "options": {
                "GS_BUCKET_NAME": GS_BUCKET_NAME,
                "GS_LOCATION": "static",
                "GS_QUERYSTRING_AUTH": False,
                "GS_DEFAULT_ACL": None,
                "GS_OBJECT_PARAMETERS": {"cache_control": "public, max-age=28800"},
            },
        },
    }

    # Set your GCP credentials
    GS_PROJECT_ID = GCP_PROJECT_ID
    GS_CUSTOM_ENDPOINT = f"{HOST_URL}"

    GS_QUERYSTRING_AUTH = False
    GS_DEFAULT_ACL = None


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    BASE_DIR / f"{APP_NAME}/assets",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# WorkOS Authentication Settings
WORKOS_API_KEY = os.environ.get("WORKOS_API_KEY", "")
WORKOS_CLIENT_ID = os.environ.get("WORKOS_CLIENT_ID", "")
WORKOS_REDIRECT_URI = os.environ.get("WORKOS_REDIRECT_URI", "http://localhost:8000/auth/callback")
